version: "2"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - php
  php:
    build: .
    restart: always
    links:
      - mysql
    volumes:
      - ./web:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yangqia
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - '8080:80'
    links:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
  composer:
    image: composer
    command: install
    volumes:
      - ./web:/app